[package]
name = "nannou_sketches"
version = "0.1.0"
authors = ["Alec Deason <alec@tinycountry.com>"]
edition = "2018"

[features]
save_frames = []

[dependencies]
nannou = "0.15.0"
rayon = "1.5.0"
mathru = "0.8.3"

[profile.dev]
opt-level = 3
debug = false
