[package]
name = "nannou_sketches"
version = "0.1.0"
authors = ["Alec Deason <alec@tinycountry.com>"]
edition = "2018"

[features]
save_frames = []

[dependencies]
nannou = "0.15.0"
clingo = { version = "0.6", features = ["derive"] }

[profile.dev]
opt-level = 3
debug = false
